In [6]:
pip install git+https://github.com/fra31/auto-attack

  Cloning https://github.com/fra31/auto-attack to /private/var/folders/8d/bk2smpf90bsd0ksdh9yqgct00000gn/T/pip-req-build-zsyglyc3
  Running command git clone --filter=blob:none --quiet https://github.com/fra31/auto-attack /private/var/folders/8d/bk2smpf90bsd0ksdh9yqgct00000gn/T/pip-req-build-zsyglyc3
  Resolved https://github.com/fra31/auto-attack to commit a39220048b3c9f2cca9a4d3a54604793c68eca7e
  Preparing metadata (setup.py) ... done
  Created wheel for autoattack: filename=autoattack-0.1-py3-none-any.whl size=36229 sha256=e7cdabcfcc6ee689f2c6c2916c70c2ebe7f39a168eda319968c614c1989c9e31
  Stored in directory: /private/var/folders/8d/bk2smpf90bsd0ksdh9yqgct00000gn/T/pip-ephem-wheel-cache-vef92x5u/wheels/e1/e8/28/65b2724d4c7740785979eb50bf5e1b3986ead22f6c32a87f8f
Successfully built autoattack
Note: you may need to restart the kernel to use updated packages.


In [9]:
import sys 
import Models
from MyTorch import Classifier
import torch 
from matplotlib import pyplot as plt 
import save_load_interface
import Metrics
import scipy.linalg
import numpy as np
import math

code_length=16
num_codes=10
#seed=59

M = scipy.linalg.hadamard(code_length).astype(np.float32) # Hadamard matrix generate processing
M = M[0:num_codes]
print("First state of Hadamard matrix\n", M)

min_hamming = int(math.pow(2, math.sqrt(code_length)-1) -1)
print("Minimum Hamming distance :", min_hamming)

# distance_matrix 만드는 함수야
def generating_distance_matrix(codebook, num_classes, code_length):
    distance_matrix = np.zeros((num_codes, num_codes), dtype=int)
    for i in range(num_codes):
        for j in range(num_codes):
            distance_matrix[i, j] = np.sum(codebook[i] != codebook[j])
    print("Distance matrix\n", distance_matrix)
    
generating_distance_matrix(M, num_codes, code_length)

First state of Hadamard matrix
 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1.  1. -1.  1. -1.  1. -1.  1. -1.]
 [ 1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.]
 [ 1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.  1.]
 [ 1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1.  1. -1. -1. -1. -1.]
 [ 1. -1.  1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  1. -1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1.  1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1. -1.  1. -1.  1. -1.  1. -1.  1.]]
Minimum Hamming distance : 7
Distance matrix
 [[0 8 8 8 8 8 8 8 8 8]
 [8 0 8 8 8 8 8 8 8 8]
 [8 8 0 8 8 8 8 8 8 8]
 [8 8 8 0 8 8 8 8 8 8]
 [8 8 8 8 0 8 8 8 8 8]
 [8 8 8 8 8 0 8 8 8 8]
 [8 8 8 8 8 8 0 8 8 8]
 [8 8 8 8 8 8 8 0 8 8]
 [8 8 8 8 8 8 8 8 0 8]
 [8 8 8 8 8 8 8 8 8 0]]


In [11]:
## optimizing codebook by bits flipping

dlist = []

cnt=0

temp = M.copy()
max = 0


ok = False 
while(not ok):
    if cnt >= 1000:
        break
    print(cnt)

    t = True
    while(t):
        row = np.random.randint(0, num_codes)
        idx = np.random.randint(0, code_length)
        
        temp_M = temp.copy()
        temp_M[row][idx] *= -1
        
        min_ham = min_hamming_distance_row(temp_M)
        max_ham = max_hamming_distance_row(temp_M)

        if min_ham >= min_hamming and max_ham > max:
            print("max_ham : ", max)
            max = max_ham
            max_M = temp_M
            temp = temp_M
            t = False
            cnt+=1
        else:
            cnt+=1
            print("Hamming distance 증가 실패")
            
dlist.append(max_M)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Users/jang-ulam/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/8d/bk2smpf90bsd0ksdh9yqgct00000gn/T/ipykernel_16140/3549741116.py", line 25, in <module>
    min_ham = min_hamming_distance_row(temp_M)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/8d/bk2smpf90bsd0ksdh9yqgct00000gn/T/ipykernel_16140/2322254734.py", line 16, in min_hamming_distance_row
    dist = hamming_distance(W[pair[0]], W[pair[1]])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/8d/bk2smpf90bsd0ksdh9yqgct00000gn/T/ipykernel_16140/2322254734.py", line -1, in hamming_distance
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jang-ulam/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2120, in s

In [13]:
print(max_ham)
print(max_M)
print(min_hamming)
min_ = min_hamming_distance_row(max_M) 
print("Min hamming distance Row: {}".format(min_))

max_ = max_hamming_distance_row(max_M) 
print("Max hamming distance Row: {}".format(max_))

W = np.load('codewords/codeword_' + str(16) + '_bit.npy', allow_pickle=True) 
W[W==0] = -1   # scale codes to [-1, 1] range instead of [0,1] and get first code of list

for i in range(len(dlist)):
    generating_distance_matrix(max_M, num_codes, code_length)
    
generating_distance_matrix(max_M, num_codes, code_length)

15
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1.  1. -1.  1. -1.  1. -1.  1. -1.]
 [ 1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.]
 [ 1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.  1.]
 [ 1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1.  1. -1. -1. -1. -1.]
 [-1.  1.  1. -1.  1.  1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1.  1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1.  1. -1. -1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1. -1.  1. -1.  1. -1.  1. -1.  1.]]
7
Min hamming distance Row: 7
Max hamming distance Row: 16
Distance matrix
 [[ 0  8  8  8  8  7  8  9  8  8]
 [ 8  0  8  8  8  9  8  7  8  8]
 [ 8  8  0  8  8  7  8  9  8  8]
 [ 8  8  8  0  8  9  8  7  8  8]
 [ 8  8  8  8  0  9  8  7  8  8]
 [ 7  9  7  9  9  0  9 16  7  9]
 [ 8  8  8  8  8  9  0  7  8  8]
 [ 9  7  9  7  7 16

In [7]:
#Main script for training ECOC ensembles

import numpy as np 
import torch.nn
import torch
import Models 
from Loss_Function import hinge_vec
import save_load_interface
from MyTorch_ecoc import Classifier_ecoc as Classifier_ecoc

# parameters for PyTorch model type and its training
dataset_name = "CIFAR10" #"CIFAR10"  or "Fashion-MNIST"
batch_size = 100
nb_epoch = 1000
lr = 0.0001 
seed = 42       
path_checkpoint = "ecoc_16_1/"  # were the checkpoints are saved
save_iter = 10                         # interval between checkpoints being saved
nb_independent_models = 16            # Number of shared feature extractors (for independent models, 16, 32 and 16 since they are independent)
nb_bits_per_model = 1
filters = [16, 32, 64] #[32, 64, 128] # params A, B, C
filter2 = [64]            # param D
RegAdvt = False          # if want to perform RegAdvt

# Set to true to load a model and resume its training
load_model = False
load_model_filename = "checkpoints/cifar10/current_experimentation/epoch_810.pth"      

# load W from files
load_codebook = False
if load_codebook:
    W = np.load('codewords/codeword_' + str(nb_bits_per_model*nb_independent_models) + '_bit.npy', allow_pickle=True) 
    W[W==0] = -1   # codewords need to be [-1, 1] instead of [0, 1]
else:
    W = max_M
    
# Init ECOC Model
model = Models.ecoc_ensemble_no_bn(W, nb_independent_models, filters, filter2, nb_independent_models*nb_bits_per_model, dataset_name) 

# ECOC Resnet Models 
model = Models.ResNetECOC(W, nb_independent_models, nb_independent_models) 

total_params = sum(param.numel() for param in model.parameters())
print(total_params)
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(trainable_params)
quit()

# Training params 
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
criterion = hinge_vec()    # hinge loss for ECOC ensembles

# Set dataset dependent params 
if dataset_name == "Fashion-MNIST": 
    input_shape = (1, 28, 28) 
    nb_classes = 10

elif dataset_name == "CIFAR10": 
    input_shape = (3, 32, 32)
    nb_classes = 10                             

print("\nTraining ECOC Model" ) 
print("Dataset: {}".format(dataset_name))
print("Batch size: {}, Nb of epochs: {}, learning rate: {}".format(batch_size, nb_epoch, lr))

#check if cuda is available. Training is much faster on the GPU. 
device = torch.device("cuda" if(torch.cuda.is_available()) else "cpu") 

if load_model: 
    checkpoint = save_load_interface.load_checkpoint(load_model_filename)
    model.load_state_dict(checkpoint['model'])
    model.to(device)  # need to do it here otherwise the optimizer parameters are on cpu instead of device (or cuda if gpu available)
    optimizer.load_state_dict(checkpoint['optimizer'])
    for g in optimizer.param_groups:  
        g['lr']= lr
    criterion = checkpoint['criterion']
    classifier = Classifier_ecoc(model, W, dataset_name, device, nb_classes, batch_size, input_shape, optimizer, criterion, seed)
    classifier.set_history(checkpoint['train_accuracy'], checkpoint['validation_accuracy'], checkpoint['train_loss'], checkpoint['val_loss'], checkpoint['euclidean_dist'], checkpoint['hamming_dist'], checkpoint['hamming_dist_val'], checkpoint['euclidean_dist_val'])
else:      
    classifier = Classifier_ecoc(model, W, dataset_name, device, nb_classes, batch_size, input_shape, optimizer, criterion, seed) 

# Train ECOC model
classifier.fit(nb_epoch, 0.98, save_iter, path=path_checkpoint, advt=RegAdvt) 




4677904
4677904

Training ECOC Model
Dataset: CIFAR10
Batch size: 100, Nb of epochs: 1000, learning rate: 0.0001
Files already downloaded and verified
Files already downloaded and verified
epoch :  0
batch :  0
batch :  1
batch :  2
batch :  3
batch :  4
batch :  5
batch :  6
batch :  7
batch :  8
batch :  9
batch :  10
batch :  11
batch :  12



KeyboardInterrupt



In [303]:
# main script for attacking ECOC ensembles 

import Models
import AdversarialAttackCleverHans
import torch
import save_load_interface
import numpy as np
import Metrics
import Dataset
from Loss_Function import cw_loss

# parameters for PyTorch model type and its training
dataset_name = "CIFAR10" #"Fashion-MNIST"  #Fashion-MNIST or CIFAR10 (must be written this way)
batch_size = 100  
seed = 42  # for making sure same images are used every time
filters = [32, 64, 128] # params A, B, C
filter2 = [16]            # param D
root = 'models_final/CIFAR10/AdvT/IndAdvt_2iter/indAdvt_2iter.pth' # for SIMPLE model, provide path of simple_1 model. For ENSEMBLE models, provide path of folder where all SIMPLE models are

# params for performing attacks 
attack_type = "PGD"      # can be 'FGSM' or 'PDG' or 'CWL2' or 'auto' For CWL2, need to save the perturbations and run the script "cw_bound.py" to get the accuracy with a L2 bound. Otherwise, the perturbations generated in this script are not bounded. 
norm = np.inf             # norm of the attack (np.inf or 2)
max_iter = 100            # max iteration for PGD attack 
es = True                 # True: PGD^es, False: PGD
plus = False              # adaptation for removing operations that could cause gradient masking (i.e., softmax in soft voter of ensemble baseline models)
epsilon =  0.031          # bound the attack norm 
eps_step = 1/3 * epsilon  # epsilon step for PGD attack
loss = cw_loss            # torch.nn.CrossEntropyLoss()   # loss function for PGD attack 
nb_images = 2000            

# Parameters
seed = 42   # to make sure we use the same images everytime 
batch_size = 1 #100
nb_independent_models = 16
nb_bits_per_model = 1
save_adversarial_examples = False

# Params for loading model and saving attack images and metrics 
path_adversaries = "current_experimentation/PGD_0_031_tanh.pth"            # where the adversarial images will be saved                             
path_metrics = "checkpoints/cifar10/current_experimentation/metrics.npz"   # where the metrics (hamm dist, codes, etc) will be saved

W = max_M

# Model architecture details for ecoc models                                                             
model = Models.ecoc_ensemble_no_bn(W, nb_independent_models, filters, filter2, nb_independent_models*nb_bits_per_model, dataset_name) 


def main(): 
    print("\nGenerating Adversarial Attack" ) 
    # check if cuda available 
    print("CUDA available: {}\n".format(torch.cuda.is_available()))
    device = torch.device("cuda" if(torch.cuda.is_available()) else "cpu") 

    # print experimentation details 
    print("Dataset: {}".format(dataset_name))
    print("Attack Type: {}, Epsilon: {}, Epsilon step: {}, Max Iter: {}, Nb Images: {}".format(attack_type, epsilon, eps_step, max_iter, nb_images))


    # get testing data
    _, test_dataset = Dataset.getDataset(dataset_name)
    test_dataloader = Dataset.get_dataLoader(test_dataset, batch_size)
 
    # Load the ECOC model from files
    checkpoint = save_load_interface.load_checkpoint(root)
    model.load_state_dict(checkpoint['model'])
    
    full_model = torch.nn.Sequential(model, Models.ecoc_decoder(torch.from_numpy(W).to(device), no_tanh=plus))  # sequence of ecoc model and decoder to output the probabilities of each class 
    full_model.to(device)
    full_model.eval()

    ### Adversarial attack (generate adversarial examples)
    test_data = Dataset.get_test_subset(test_dataset, batch_size, nb_images, seed=seed)
    if attack_type == 'FGSM':
        data_perturbed = AdversarialAttackCleverHans.FGSM(full_model, batch_size, test_data, epsilon, norm)             
    elif attack_type == 'PGD':
        data_perturbed = AdversarialAttackCleverHans.PGD(full_model, batch_size, test_data, epsilon, eps_step, max_iter, norm, loss, early_stop=True)
    elif attack_type == 'CW':
        data_perturbed = AdversarialAttackCleverHans.CW_L2(full_model, batch_size, test_data, max_iter=max_iter)
    elif attack_type == 'auto': 
        data_perturbed = AdversarialAttackCleverHans.autoAttack(full_model, batch_size, test_data, epsilon, norm)


    # compute accuracy before and after the attack
    predictions_clean, true_labels_clean = Metrics.predict_eval(full_model, test_data, device) 
    predictions_perturbed, true_labels_perturbed = Metrics.predict_eval(full_model, data_perturbed, device)
    accuracy_clean = Metrics.score(predictions_clean, true_labels_clean) 
    accuracy_perturbed = Metrics.score(predictions_perturbed, true_labels_perturbed)    
    asr = Metrics.success_rate(predictions_clean, true_labels_clean, predictions_perturbed)
    print("Test accuracy before the attack: {}".format(accuracy_clean))
    print("Accuracy of classifier against attack: {}".format(accuracy_perturbed))
    print("Attack success rate: {}".format(asr))

  
    # Save adversarial examples
    if save_adversarial_examples: 
        save_load_interface.save_adversarial_examples(path_adversaries, data_perturbed)
    
        # save a bunch of metrics to file for later analysis
        labels_list, pred_labels_list, true_codes_list, inferred_codes_list, real_inferred_codes_list = Metrics.assess_codes(full_model, data_perturbed, torch.from_numpy(W).to(device), device) 
        labels_list = labels_list.numpy()
        pred_labels_list = pred_labels_list.numpy()
        true_codes_list = true_codes_list.numpy()
        inferred_codes_list = inferred_codes_list.numpy()
        real_inferred_codes_list = real_inferred_codes_list.numpy()
        np.savez(path_metrics, true_labels=labels_list, pred_labels_clean=predictions_clean, predicted_labels=pred_labels_list, true_codes=true_codes_list, predicted_codes=inferred_codes_list, real_predicted_codes=real_inferred_codes_list)

if __name__ == "__main__": 
    main() 



Generating Adversarial Attack
CUDA available: False

Dataset: CIFAR10
Attack Type: PGD, Epsilon: 0.031, Epsilon step: 0.010333333333333333, Max Iter: 100, Nb Images: 2000


100%|████████████████████████| 170498071/170498071 [00:38<00:00, 4430891.22it/s]


Extracting datasets/cifar10/cifar-10-python.tar.gz to datasets/cifar10
Files already downloaded and verified
Error: the file name for the checkpoint doesn't exists


TypeError: 'bool' object is not subscriptable

In [242]:
print(max_M)
for i in range(num_codes):
    for j in range(code_length):
        if M[i][j] != max_M[i][j] :
            print(i, j)

print(min_hamming_distance_row_complement(max_M))
print(min_hamming_distance_column(max_M))

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1. -1.  1. -1. -1.]
 [ 1.  1. -1. -1.  1. -1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.]
 [ 1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.  1.]
 [ 1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1.  1. -1. -1. -1. -1.]
 [ 1. -1.  1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  1. -1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1.  1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1. -1. -1.  1. -1.  1.  1. -1.  1. -1. -1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1. -1.  1. -1.  1. -1.  1. -1.  1.]]
1 0
1 2
1 4
1 6
1 8
1 11
1 12
1 13
1 14
2 5
16
2


In [5]:
# Function to compute min hamming distance between all possible pairs of codewords from the W matrix 
def min_hamming_distance_row(W):
    '''
    Compute minimum hamming distance between rows of a matrix of codewords

            parameters: W (numpy 2d array): matrix of codewords

            Returns: min hamming_distance (int) : minimum hamming distance 
    ''' 
    nb_rows = W.shape[0]
    nb_columns = W.shape[1]
    pairs = [(i, j) for i in range(nb_rows) for j in range(i+1, nb_rows)] 
    min = W.shape[1]
    dlist = []
    for pair in pairs:
        dist = hamming_distance(W[pair[0]], W[pair[1]])
        dlist.append(dist)
        if dist < min: 
            min = dist
    return min

def max_hamming_distance_row(W):
    '''
    Compute maximum hamming distance between rows of a matrix of codewords

            parameters: W (numpy 2d array): matrix of codewords

            Returns: min hamming_distance (int) : minimum hamming distance 
    ''' 
    nb_rows = W.shape[0]
    nb_columns = W.shape[1]
    pairs = [(i, j) for i in range(nb_rows) for j in range(i+1, nb_rows)] 
    max = 0
    dlist = []
    for pair in pairs:
        dist = hamming_distance(W[pair[0]], W[pair[1]])
        dlist.append(dist)
        if dist > max: 
            max = dist
    return max

def min_hamming_distance_row_complement(W):
    '''
    Compute minimum hamming distance between rows of a matrix of codewords

            parameters: W (numpy 2d array): matrix of codewords

            Returns: min hamming_distance (int) : minimum hamming distance 
    ''' 
    nb_rows = W.shape[0]
    nb_columns = W.shape[1]
    pairs = [(i, j) for i in range(nb_rows) for j in range(i+1, nb_rows)] 
    min = W.shape[1]
    dlist = []
    for pair in pairs:
        dist = hamming_distance(1 - W[pair[0]], W[pair[1]])
        dlist.append(dist)
        if dist < min: 
            min = dist
    for pair in pairs:
        dist = hamming_distance(W[pair[0]], 1 - W[pair[1]])
        dlist.append(dist)
        if dist < min: 
            min = dist
    return min

def min_hamming_distance_column(W):
    '''
    Compute minimum hamming distance betweem rows of a matrix of codeword 

            parameters: W (numpy 2d array): matrix of codewords

            Returns: min hamming_distance (int) : minimum hamming distance 
    ''' 
    nb_rows = W.shape[0]
    nb_columns = W.shape[1]

    pairs = [(i, j) for i in range(nb_columns) for j in range(i+1, nb_columns)] 
    min = W.shape[0]
    dlist = []
    for pair in pairs: 
        dist = hamming_distance(W[:, pair[0]], W[:, pair[1]])
        dlist.append(dist)
        if dist < min: 
            min = dist 
    count = 0 
    tot = 0
    nb_zero = 0
    for item in dlist: 
        count+= 1 
        tot += item
        if item == 0 : 
            nb_zero += 1 

    return min 


def ham_dist_col(W, val):
    '''
    Compute minimum hamming distance betweem rows of a matrix of codeword 

            parameters: W (numpy 2d array): matrix of codewords

            Returns: min hamming_distance (int) : minimum hamming distance 
    ''' 
    flag = 0
    nb_columns = W.shape[1]
    pairs = [(i, j) for i in range(nb_columns) for j in range(i+1, nb_columns)] 
    dlist = []
    for pair in pairs: 
        dist = hamming_distance(W[:, pair[0]], W[:, pair[1]])
        print(dist)
        dlist.append(dist)
        if dist > val: 
            flag = 1
    return flag
    
def min_hamming_distance_column_complement(W):
    '''
    Compute minimum hamming distance betweem rows of a matrix of codeword 

            parameters: W (numpy 2d array): matrix of codewords

            Returns: min hamming_distance (int) : minimum hamming distance 
    ''' 
    nb_rows = W.shape[0]
    nb_columns = W.shape[1]

    pairs = [(i, j) for i in range(nb_columns) for j in range(i+1, nb_columns)] 
    min = W.shape[0]
    dlist = []
    for pair in pairs: 
        dist = hamming_distance(1 - W[:, pair[0]], W[:, pair[1]])
        dlist.append(dist)
        if dist < min: 
            min = dist 
    count = 0 
    tot = 0
    for item in dlist: 
        count+= 1 
        tot += item

    for pair in pairs: 
        dist = hamming_distance(W[:, pair[0]], 1 - W[:, pair[1]])
        dlist.append(dist)
        if dist < min: 
            min = dist 
    count = 0 
    tot = 0
    for item in dlist: 
        count+= 1
        tot += item

    return min

# Function to compute hamming distance between two codewords
def hamming_distance(a, b): 
    '''
    Compute hamming distance between a and b 

            parameters: a, b (numpy arrays): input vectors (mush have the same length)

            Returns: hamming_distance (int) : hamming distance 
    '''
    count = 0
    if a.shape == b.shape: 
        for i, elem in enumerate(a): 
            if elem != b[i]: 
                count += 1             
    else: 
        print("Cannot compute hamming distance between two vectors of different sizes")
    return count
